### ISSUE TITLE
issue merging ignores" configurations

### ISSUE THREAD

**Issue by tinchoz49** [shipitjs/shipit#51] opened 2015-03-30 17:33 UTC
If you write something like: 

```
shipit.initConfig({
    default: {
      ignores: ['.git', 'node_modules'],
    },
    staging: {
      servers: 'user@myserver.com'
    }
  })
```

**Comment by neoziro** [comment] 2015-03-30 18:40
Duplicate of #52

**Closed** 2015-03-30 18:40 UTC
