### ISSUE TITLE
Dynamic list of servers

### ISSUE THREAD

**Issue by xgalen** [shipitjs/shipit#131] opened 2016-08-05 15:56 UTC
Hi,

In my company we use AWS and deploy on multiple servers (dynamic, on-demmand). Since it is a scalable platform, we don't know the list of servers by default and we can't hardcode them on the `shipitfile.js`.

It would be nice if we can apply the `shipitConfig` through a callback or similar; then we can get the list of servers and pass it to `shipitConfig` synchronously to deploy as needed.

Please, any suggestion how can we do this? Thanks in advance.

**Comment by travco** [comment] 2016-08-11 13:18
My initial thought is that you can require files with Node. So if you were to say have a file that is awsServers.json, that you have automatically written every time the servers change, you could import that file as the servers array in your shipitfile.

E.g.
```
module.exports = function (shipit) {
awsServers = require('awsServers.json');

  shipit.initConfig({
    default: {},
    staging: {
      servers: awsServers;
    }
  });

...
};
```

Best way I can think of to solve it, as anything we do in shipit will likely boil down to the same method. Any reason why that wouldn't work @xgalen ?

**Comment by xgalen** [comment] 2016-08-11 16:20
That would work but is very ugly, imho.
While having aws/ec2 functions with callbacks to get the servers' list dynamically, I think read from a file is a bad solution (problems writing a file).

I think something like this is better. More robust and scalable, avoiding problems writing a file:

```
getServersList(function(error, awsServers) {
    if (error) return new Error();
    shipit.initConfig({
        default: {},
        staging: {
             servers: awsServers
        }
     });
    ...
});
```

**Comment by travco** [comment] 2016-08-11 20:35
Well, other option I can think of (assuming that you have a function that retrieves your AWS servers like `getServersList`) is to resolve the server listings as part of the config - relatively cleaner.
```js
module.exports = function (shipit) {
awsServers = require('./getservers.js').getServersList;

  shipit.initConfig({
    default: {},
    staging: {
      servers: awsServers();
    }
  });

...
};
```
Frankly there's a lot of ways to "skin the cat" here that aren't something that requires additional functionality. You can already programmatically start and define the config in shipit, you just need to have the variables (server lists) available from wherever your calling it.

**Comment by rfunduk** [comment] 2016-08-13 18:11
I think the issue @xgalen is trying to get solved is that `getServers` might be async itself (eg, not loading from a file but actually doing API calls to AWS or similar). So you want to write code like this (starting from your example):

```js
module.exports = function (shipit) {
  getServers = require('./getservers.js').getServersList;
  getServers().then( function( awsServers ) {
    shipit.initConfig({
      default: {},
      staging: {
        servers: awsServers
      }
    });
  } );
  ...
};
```

And that would be fine except that in `bin/shipit` that isn't supported. It just requires and calls the function in `shipitfile.js` and immediately calls `shipit.initialize()`, etc. Since the config is still not actually defined, all of those calls fail.

I also needed this feature, so I made a relatively simple change to `bin/shipit` to just capture the return value of the function exported from `shipitfile.js`, check if it's an instance of `Promise`, and if it is, then just wait for it to resolve before doing the rest of the initialization (otherwise carry on as usual, of course).

If this is something you'd be willing to accept a PR for, let me know and I'll do that.

**Comment by xgalen** [comment] 2016-08-16 08:34
Yeah, that's it @rfunduk The function  which get the servers is async :)
I think do not accept async functions to configure shipit is lose a great feature of node.

**Comment by rfunduk** [comment] 2016-08-16 12:21
@xgalen in my case I am doing some significant async work before the config can be ready, so this is a must. If you're in the same boat you might want to use my fork (hopefully temporarily until this gets merged) - https://github.com/rfunduk/shipit

**Comment by alexfernandez** [comment] 2016-08-16 14:53
@rfunduk Yes, please send a PR, we need this functionality! Is it possible to do it so that it works both sync (if there is no callback) and async (when there is a callback)?

**Comment by rfunduk** [comment] 2016-08-16 14:57
@alexfernandez Oh absolutely! That's what I did. It checks if the return value of the function exported from `shipitfile.js` is a `Promise`. If it's not (as is normally the case when just using `initConfig` directly as usual) then nothing is different. It's only when you specifically return a promise does it wait to initialize everything. PR incoming later today :+1:

**Comment by alexfernandez** [comment] 2016-08-16 15:32
@rfunduk Oh, and would it work with a callback? Pardon my ignorance, we are not currently using promises :(

**Comment by rfunduk** [comment] 2016-08-16 15:44
Hm I'm not really sure how to make that happen. The problem is this line in `bin/shipit`: https://github.com/shipitjs/shipit/blob/b018f742da4131f430b5175e1e51abe031008413/bin/shipit#L75

So the only way we have to detect whether or not it should be handled async is to check the return value. Imagine this code:

```js
module.exports = function( shipit ) {
  somethingAsync( function() {
    shipit.initConfig( { ... } )
  } )
}
```

So `bin/shipit` requires this file and runs the default export. The return value is undefined. How should `bin/shipit` decide whether or not `initConfig` has been called yet or not? How does it know you're waiting? Even if we decide on something implicit like just returning `false` if you want it to be async, what then is the trigger for doing the initialization?

If you have an async function that doesn't use promises and you don't want to modify it, you should be able to just wrap it in this function as a special-case. Something like:

```js
module.exports = function( shipit ) {
  return new Promise( function( resolve ) {
    yourAsyncFunctionWithCallback( function(...) {
      shipit.initConfig( { ... } )
      resolve()
    } )
  } )
}
```

Finally I could add a second param when `bin/shipit` calls the `shipitfile.js` function. Like this:

```js
require(shipfile)(shipit, done)
```

And then require the user writing `shipitfile.js` to call it when they're done calling `initConfig`. But that will break everyone's `shipitfile.js`, and I'm not sure how to then handle the promise case - which IMO is much more useful and common these days.

**Comment by alexfernandez** [comment] 2016-08-17 16:19
I see the difficulty. Your approach is cool!

**Comment by alexfernandez** [comment] 2016-08-17 16:22
I see the difficulty. Your approach is cool! Have you already sent the PR? I don't see it in the list. It would make shipIt usable for us too!

**Comment by rfunduk** [comment] 2016-08-17 16:23
Yea sorry about the dely. Typing this with one hand and feeding a baby with the other :) I hope to get to it today.

**Comment by alexfernandez** [comment] 2016-08-17 16:27
No pressure! PRs can wait :)

**Closed** 2016-11-13 02:48 UTC
